name: TrOCR_custom_training
channels:
  - conda-forge
dependencies:
  - python=3.10
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - torch
  - pip:
    - accelerate
    - jiwer
    - commitizen
    - python-dotenv
    - transformers
    - datasets
    - evaluate
    - scikit-learn