name: TrOCR_custom_training
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - pip:
    - accelerate
    - jiwer
    - commitizen
    - python-dotenv
    - transformers
    - datasets
    - evaluate
    - scikit-learn